experiment_name: "spmm_spmm"
implementations:
#  - name: "SpMM_SpMM_CSC_Interleaved_Atomic_FusedParallel"
#    color: "green"
#    tuned: True
#    tune_parameter: "Iter Per Partition"
#  - name: "SpMM_SpMM_CSC_Separated_FusedParallel"
#    color: "blue"
#    tuned: True
#    tune_parameter: "Iter Per Partition"
  - name: "SpMM_SpMM_CSC_Interleaved_Coloring_FusedParallel"
    color: "red"
    tuned: True
    tune_parameters:
    - "MTile"
  - name: "SpMM_SpMM_CSC_Interleaved_Coloring_FusedParallel_KTiling"
    color: "red"
    tuned: True
    tune_parameters:
      - "MTile"
      - "NTile0"
  - name: "SpMM_SpMM_CSC_Interleaved_Coloring_FusedParallel_KTiling"
    color: "red"
    tuned: True
    tune_parameter: "MTile"
  - name: "SpMM_SpMM_Demo_UnFusedParallel"
    color: "orange"
    tuned: False
#  - name: "SpMM_SpMM_Separated_FusedParallel"
#    color: "purple"
#    tuned: True
#    tune_parameter: "Iter Per Partition"
#  - name: "SpMM_SpMM_Mixed_FusedParallel"
#    color: "brown"
#    tuned: True
#    tune_parameter: "Iter Per Partition"
  - name: "SpMM_SpMM_FusedParallel"
    color: "gray"
    tuned: True
    tune_parameters:
    - "Iter Per Partition"
feature_sizes:
  - 64
matrices:
  - "pubmed_ordered.mtx"
  - "cora_ordered.mtx"
  - "cora_full_ordered.mtx"
baseline: "SpMM_SpMM_Demo_UnFusedParallel"